#!/usr/bin/env bash

recv() {
  echo "< $@" >&2;
}

send() {
  echo "> $@" >&2
  printf '%s\r\n' "$*"
}

DATE=$(date +"%a, %d %b %Y %H:%M:%S %Z")

declare -a headers

while read -r line; do
   line=${line%%$'\r'}
   recv "$line"

   # If we've reached the end of the headers, break.
   [ -z "$line" ] && break

   headers+=("$line")
done

. "$1"
