#!/usr/bin/env bash
set -e
export -n CDPATH

if [ "$1" = "--debug" ]; then
  export AZK_DEBUG=1
  shift
fi

if [ -n "$AZK_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "azk: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

defaul_root=$(abs_dirname "$(abs_dirname $BASH_SOURCE)/../")
source "${defaul_root}/private/bin/common.sh"

if [ -z "${AZK_ROOT}" ]; then
  AZK_ROOT="${defaul_root}"
else
  AZK_ROOT="${AZK_ROOT%/}"
fi
export AZK_ROOT

if [ -z "${AZK_DIR}" ]; then
  AZK_DIR="$(pwd)"
else
  cd "$AZK_DIR" 2>/dev/null || {
    azk.error  "cannot change working directory to \`$AZK_DIR'"
    exit 1
  } >&2
  AZK_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export AZK_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${AZK_ROOT}/plugins/"*/bin; do
  bin_path="${bin_path}:${plugin_bin}"
done
export PATH="${bin_path}:${PATH}"

hook_path="${AZK_HOOK_PATH}:${AZK_ROOT}/azk.d:/usr/local/etc/azk.d:/etc/azk.d:/usr/lib/azk/hooks"
for plugin_hook in "${AZK_ROOT}/plugins/"*/etc/azk.d; do
  hook_path="${hook_path}:${plugin_hook}"
done
export AZK_HOOK_PATH="$hook_path"

shopt -u nullglob

# Private extensions
export PATH="${AZK_ROOT}/private/bin:${PATH}"

command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(azk-version)\n$(azk-help)" >&2
  ;;
"-v" )
  exec azk-version
  ;;
* )
  command_path="$(command -v "azk-$command" || true)"
  if [ -z "$command_path" ]; then
    azk.error "no such command \`$command'"
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac

