#!/usr/bin/env bash
# Summary: Azk agent administrator
# Usage: azk admin <command>

set -e
[ -n "$AZK_DEBUG" ] && set -x

# Provide azk completions
if [ "$1" = "--complete" ]; then
  exit
fi

# Command
agent_command="$1";
case "${agent_command:-status}" in
  destroy|suspend|resume|provision)
    cd `azk-root`
    exec vagrant $agent_command
    ;;
  up|reload)
    exec vagrant "$agent_command" --provision
    ;;
  status)
    exec azk agent-status
    ;;
  *)
    [ ! -z "$agent_command" ] && azk.error "'$agent_command' unsupported command"
    azk-help --usage admin >&2
    exit 1;
esac
