#!/usr/bin/env bash
# Summary: Search azk file in current project
set -e
[ -n "$AZK_DEBUG" ] && set -x

find_local_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ -e "${root}/azkfile.json" ]; then
      echo "${root}/azkfile.json"
      exit
    fi
    root="${root%/*}"
  done
}

file=$(
  find_local_file "$AZK_DIR"
  [ "$AZK_DIR" = "$PWD" ] || find_local_file "$PWD"
)

if [ -z "$file" ]; then
  echo "azk: no such azkfile.json in current project" >&2
  exit 1
else
  # Valid azk file
  if cat $file | jq "." 1>/dev/null; then
    echo $file
  else
    echo "azk: '$file' is not valid json format" >&2
    exit 1;
  fi
fi
