#!/usr/bin/env bash
#
# Summary: Performs the provisioning of specified image type
#
# Usage: azk provision <image-type>

set -e
[ -n "$AZK_DEBUG" ] && set -x

image_type="$1"

# requires parameter
if [ -z "$image_type" ]; then
  azk-help --usage provision >&2
  exit 1
fi

# requires azkfile
azkfile=`azk-azkfile`

# run only is --final command
if [ ! "$1" = "--final" ]; then
  exec azk-agent-exec provision $@
fi; shift

# env
AZK_DATA_PATH=${AZK_DATA_PATH:-`azk root`/data}

meta() {
  eval "$(cat <&0 | jq "$@ | @sh \"echo \(.)\"" | sed 's:^"::g' | sed 's:"$::g')"
}

github() {
  exec sed -n 's:\([:alnum:]*\)/\([[:alnum:]|-]*\)#\(.*\):\1 \2 \3:p'
}

# TODO: Refectory to use a common functions
azk.info() {
  if [ -z "$TERM" ]; then
    echo "azk: $1"
  else
    echo "$(tput setaf 4)azk$(tput sgr0): $1"
  fi
}

clone_or_update() {
  is_repo=$(git --git-dir="$2/.git" rev-parse &>/dev/null; echo $?)
  if [ "$is_repo" -eq 0 ] ; then
    azk.info "check for box updates in '$1#$3'..."
    git --git-dir="$2/.git" remote update >/dev/null
  else
    echo "azk: get box '$1#$3'..."
    git clone $1 $2 >/dev/null
  fi
  return $?
}

# TODO: Add support generic git repo
# TODO: Add support to relative path repository
# TODO: Add suporte a laste version
# TODO: Pull base image
provision_box() {
  # Box information
  read -r user repo vers <<<"$(cat $azkfile | meta ".box" | github)"
  image="azk/boxes:${user}_${repo}_${vers}"

  # Search image
  azk.info "searching '$image'"
  id=$(azk-dcli --final /images/$image/json 2>/dev/null || echo "{}")
  id=$(echo $id | meta ".id")
  if [ "${id}" != "null" ]; then
    azk.info "'$image' already provisioned"
    exit 0
  fi

  azk.info "'$image' not found"

  # Clone repository
     clone_url="https://github.com/$user/$repo"
    clone_path="${AZK_DATA_PATH}/boxes/$user/$repo"

  if ! clone_or_update $clone_url $clone_path $vers ; then
    azk.info "could not get or update the box $clone_url repository"
    exit 1;
  fi

  # Checkout version
  azk.info "check for version '$vers'..."
  git --git-dir=$clone_path/.git checkout --quiet $vers # &>/dev/null

  # Generate image
  azk-image-generate box $clone_path $image
}

image_type="$1"
case $image_type in
  box)
    provision_box
esac

