#!/usr/bin/env bash
#
# Summary: Run an command it has as dependence the agent
#
# Usage: azk agent-exec <azk-command> [arg1 arg2...]

set -e
[ -n "$AZK_DEBUG" ] && set -x

# Provide azk completions
if [ "$1" = "--complete" ]; then
  exec azk-commands
fi

if [ "$1" = "--final" ]; then
  final=true; shift
fi

azk_command="$1"

if [ -z "$azk_command" ]; then
  azk-help --usage agent-exec >&2
  exit 1
fi

check_agent() {
  [ $(ssh "${1}" "echo 1" &>/dev/null; echo $?) -eq 0 ] && return 0
  return 1
}

# find docker command
case `type -t docker` in
  file|function|alias)
    command=$1; shift
    azk $command --final $@
    ;;
  *)
     host=${AZK_AGENT_HOST:-azk-agent}
    check=$(check_agent $host; echo $?)
    if [ ! -z "$final" -o "$check" -eq 1 ]; then
      echo "azk: cannot find docker or agent" >&2
      exit 1
    fi

    echo "agent"
    exit 0
esac

