#!/usr/bin/env bash
# Summary: Configure the shell environment for azk
# Usage: eval "$(azk sh-init - [--no-rehash] [<shell>])"

set -e
[ -n "$AZK_DEBUG" ] && set -x

print=""
for args in "$@"
do
  if [ "$args" = "-" ]; then
    print=1
    shift
  fi
done

shell="$1"
if [ -z "$shell" ]; then
  shell="$(ps c -p $(ps -p $$ -o 'ppid=' 2>/dev/null) -o 'comm=' 2>/dev/null || true)"
  shell="${shell##-}"
  shell="$(basename "${shell:-$SHELL}")"
fi

READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "azk: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

root="$(abs_dirname "$0")/.."

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    profile='~/.bash_profile'
    ;;
  zsh )
    profile='~/.zshrc'
    ;;
  ksh )
    profile='~/.profile'
    ;;
  fish )
    profile='~/.config/fish/config.fish'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load azk automatically by adding"
    echo "# the following to ${profile}:"
    echo
    case "$shell" in
    fish )
      echo '. (azk init -|psub)'
      ;;
    * )
      echo 'eval "$(azk init -)"'
      ;;
    esac
    echo
  } >&2

  exit 1
fi

case "$shell" in
fish )
  echo "setenv AZK_SHELL $shell"
;;
* )
  echo "export AZK_SHELL=$shell"
;;
esac

completion="${root}/completions/azk.${shell}"
if [ -r "$completion" ]; then
  case "$shell" in
  fish ) echo ". '$completion'" ;;
  *    ) echo "source '$completion'" ;;
  esac
fi

case "$shell" in
fish )
  cat <<EOS
function azk
  set command \$argv[1]
  set -e argv[1]
  command azk "\$command" \$argv
end
EOS
  exit 0
  ;;
ksh )
  cat <<EOS
function azk {
  typeset command
EOS
  ;;
* )
  cat <<EOS
azk() {
  local command
EOS
  ;;
esac

IFS="|"
cat <<EOS
  command="\$1"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  command azk "\$command" "\$@"
}
EOS
