#!/usr/bin/env bash
#
# Summary: Run a command in azk agent with ssh
#
# Usage: azk agent-ssh [command] [arg1 arg2...]

AZK_COMMAND="$1"

if [ -z "$AZK_COMMAND" ]; then
  azk-help --usage agent-ssh >&2
  exit 1
fi

user="core"
port="22"
host=$1; shift
options="-o DSAAuthentication=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=FATAL -o IdentitiesOnly=yes"

READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "azk: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

root="$(abs_dirname "$0")/.."
identify="-i $root/private/etc/insecure_private_key"

ssh $user@$host $options $identify $@
