#!/usr/bin/env bash
# Usage: azk completions <command> [arg1 arg2...]

set -e
[ -n "$AZK_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  azk-help --usage completions >&2
  exit 1
fi

COMMAND_PATH="$(command -v "azk-$COMMAND")"
if grep -i "^\([#%]\|--\|//\) provide azk completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
