#!/usr/bin/env bash
# Summary: Display the azk root directory

BASH_SOURCE="${BASH_SOURCE:-$0}"

__FOLDER__="$(dirname $BASH_SOURCE)"
__TARGET__=$(dirname `readlink $BASH_SOURCE` 2>/dev/null || echo "")

if [ ! -z "$__TARGET__" ]; then
  if [[ "$__TARGET__" =~ ^/.*$ ]]; then
    __FOLDER__="$__TARGET__"
  else
    __FOLDER__="${__FOLDER__}/${__TARGET__}"
  fi
fi

echo "${AZK_ROOT:-$(cd ${__FOLDER__}/..; pwd)}"
