#!/usr/bin/env bash
#
# Summary: Performs the provisioning of specified image type
#
# Usage: azk provision <image-type>

set -e
[ -n "$AZK_DEBUG" ] && set -x

image_type="$1"

# TODO: Adding completions
# requires parameter
if [ -z "$image_type" ]; then
  azk-help --usage provision >&2
  exit 1
fi

# requires azkfile
azkfile=`azk-azkfile`

case "$1" in
  # run only is --final command
  --final)
    shift
    ;;
  # Only return a image name?
  --get-name)
    get_name=true
    shift
    ;;
  *)
    exec azk-agent-exec provision $@
esac

# env
AZK_DATA_PATH=${AZK_DATA_PATH:-`azk root`/data}

meta() {
  eval "$(cat <&0 | jq "$@ | @sh \"echo \(.)\"" | sed 's:^"::g' | sed 's:"$::g')"
}

github() {
  exec sed -n 's:\([:alnum:]*\)/\([[:alnum:]|-]*\)#\(.*\):\1 \2 \3:p'
}

# TODO: Refectory to use a common functions
azk.debug() {
  local color=$1; shift
  if [ -z "$TERM" ]; then
    echo "azk:$image_label $@"
  else
    echo "$(tput setaf $color)azk$(tput sgr0):$image_label $@"
  fi
}

azk.info() {
  azk.debug 4 $@
}

azk.error() {
  azk.debug 1 $@
}

clone_or_update() {
  is_repo=$(git --git-dir="$2/.git" rev-parse &>/dev/null; echo $?)
  if [ "$is_repo" -eq 0 ] ; then
    azk.info "check for box updates in '$1#$3'..."
    git --git-dir="$2/.git" remote update >/dev/null
  else
    azk.info "get box '$1#$3'..."
    git clone $1 $2 >/dev/null
  fi
  return $?
}

search_return_image() {
  local image="$1"

  # Return image name
  if [ ! -z "$get_name" ]; then
    echo "$image"
    exit 0;
  fi

  azk.info "searching: '$image'"
  local id=$(azk-dcli --final /images/$image/json 2>/dev/null || echo "{}")
  id=$(echo $id | meta ".id")

  if [ "${id}" != "null" ]; then
    azk.info "already provisioned: '$image'"
    exit 0
  fi

  azk.info "not found: '$image'"
}

# TODO: Add support generic git repo
# TODO: Add support to relative path repository
# TODO: Add suporte a laste version
# TODO: Pull base image
provision_box() {
  # Image information
  read -r user repo vers <<<"$(cat $azkfile | meta ".box" | github)"
  local image="azk/boxes:${user}_${repo}_${vers}"

  # Search image
  search_return_image $image

  # Clone repository
  local  clone_url="https://github.com/$user/$repo"
  local clone_path="${AZK_DATA_PATH}/boxes/$user/$repo"

  if ! clone_or_update $clone_url $clone_path $vers ; then
    azk.info "could not get or update the box $clone_url repository"
    exit 1;
  fi

  # Checkout version
  azk.info "check for version '$vers'..."
  git --git-dir=$clone_path/.git checkout --quiet $vers # &>/dev/null

  # Generate image
  azk-image-generate box $clone_path $image
}

provision_app() {
  # Image information
  local id="$(cat $azkfile | meta ".id")"
  local image="azk/apps:$id"

  # Search image
  search_return_image $image

  # Check box provision
  azk-provision --final box

  # Generate image
  azk-image-generate app `pwd` $image
}

image_type="$1"
case $image_type in
  box|app)
    image_label=" [image-${image_type}]"
    eval "provision_$image_type"
    ;;
  *)
    azk.error "'$image_type' unsupported image type" >&2
    exit 1;
esac

