#!/usr/bin/env bash
# Summary: Display the azk root directory

 __FILE__="${BASH_SOURCE}"
_DEFAULT_PATH=${_AZK_PATH:-`cd \`dirname $(readlink ${__FILE__} || echo ${__FILE__} )\`/..; pwd`}

echo ${AZK_ROOT:-$_DEFAULT_PATH}
