#!/usr/bin/env bash
#
# Summary: Request a url to docker service
#
# Usage: azk dcli <query>

set -e
[ -n "$AZK_DEBUG" ] && set -x

# run only is --final command
if [ ! "$1" = "--final" ]; then
  exec azk-agent-exec dcli $@
fi; shift

# Tools
source "$(azk-root)/private/bin/common.sh"

# Docker socket
AZK_DOCKER_SOCKET=${AZK_DOCKER_SOCKET:-/var/run/docker.sock}
socket=$(find $AZK_DOCKER_SOCKET -type s 2>/dev/null | head -n 1)
if [ -z "$socket" ]; then
  azk.error "requires docker socket is open"
  exit 1;
fi

# Request data
path="$1"

# Headers request
declare -a request
request+=("GET ${path} HTTP/1.1")
request+=('Host: localhost:8080')

# Format headers request
printf -v request '%s\r\n' "${request[@]}"

# Request
response_raw="$(echo -en "$request" '\r\n\n' | socat -t20 unix:$socket stdio)"

# Code returned
read -r _proto code desc <<<$(echo "$response_raw" | head -n 1)
if [ ! "$code" -eq 200 ]; then
  desc="${desc%%$'\r'}"
  azk.error "error to request ${path} => ${code} ${desc}"
  exit 1;
fi

if [ -z "$(echo "$response_raw" | grep "Transfer-Encoding: chunked")" ]; then
  body="$(echo "$response_raw" | tail -n 1)"
else
  body="$(echo "$response_raw" | tail -n 3 | head -n 1)"
fi

echo "${body%%$'\r'}"
