#!/usr/bin/env bash
#
# Summary: Run an executable with the image-app
#
# Usage: azk exec <command> [arg1 arg2...]

set -e
[ -n "$AZK_DEBUG" ] && set -x

# Provide azk completions
if [ "$1" = "--complete" ]; then
  exit
fi

# Save --final flag
if [ "$1" = "--final" ]; then
  final=true; shift
fi

exec_command="$@"
if [ -z "$exec_command" ]; then
  azk-help --usage exec >&2
  exit 1
fi

# requires azkfile
azkfile=`azk-azkfile`

# run only is --final flag
if [ -z "$final" ]; then
  exec azk-agent-exec exec $@
fi

# Check provision
image=$(azk-image-provision --get-name app)
azk-image-provision app

# Run with docker
docker run $image "$@"
